# Generated by Django 6.0.6 on 2026-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('mark', models.PositiveIntegerField(null=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE')], max_length=50, null=True)),
                ('course_image', models.ImageField(null=True, upload_to='media/course')),
                ('start_date', models.DateField(null=True)),
            ],
        ),
    ]
